-- Create custom types
create type public.user_role as enum ('ADMIN', 'RESIDENT');
create type public.booking_status as enum ('CONFIRMED', 'CANCELLED');
create type public.announcement_priority as enum ('LOW', 'HIGH');

-- Profiles Table
create table public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  unit_number text,
  role user_role default 'RESIDENT'::user_role
);

alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Amenities Table
create table public.amenities (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default now(),
  name text not null,
  description text,
  capacity integer default 1,
  image_url text,
  open_time time default '08:00:00'::time without time zone,
  close_time time default '22:00:00'::time without time zone
);

alter table public.amenities enable row level security;
create policy "Amenities are viewable by authenticated users." on amenities for select to authenticated using (true);
create policy "Admins can manage amenities." on amenities for all using (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'ADMIN'::user_role));

-- Bookings Table
create table public.bookings (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default now(),
  user_id uuid references public.profiles not null,
  amenity_id uuid references public.amenities not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  status booking_status default 'CONFIRMED'::booking_status
);

alter table public.bookings enable row level security;
create policy "Users can view their own bookings." on bookings for select using (auth.uid() = user_id);
create policy "Admins can view all bookings." on bookings for select using (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'ADMIN'::user_role));
create policy "Users can create bookings." on bookings for insert with check (auth.uid() = user_id);
create policy "Users can cancel their own bookings." on bookings for update using (auth.uid() = user_id);
create policy "Admins can cancel any booking." on bookings for update using (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'ADMIN'::user_role));


-- Announcements Table
create table public.announcements (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default now(),
  title text not null,
  message text not null,
  priority announcement_priority default 'LOW'::announcement_priority
);
alter table public.announcements enable row level security;
create policy "Announcements are viewable by authenticated users." on announcements for select to authenticated using (true);
create policy "Admins can create announcements." on announcements for insert with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'ADMIN'::user_role));


-- App Settings Table
create table public.app_settings (
  id bigint generated by default as identity primary key,
  booking_anticipation_days integer default 1 not null
);

alter table public.app_settings enable row level security;
create policy "Settings are viewable by authenticated users." on app_settings for select to authenticated using (true);
create policy "Admins can update settings." on app_settings for all using (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'ADMIN'::user_role));

-- Seed Data
insert into public.amenities(name, description, capacity, image_url) values
('Pool', 'Outdoor swimming pool.', 20, 'https://picsum.photos/800/600?random=1'),
('Gym', 'Fully equipped fitness center.', 15, 'https://picsum.photos/800/600?random=2'),
('Clubhouse', 'A great place to host parties.', 50, 'https://picsum.photos/800/600?random=3');

insert into public.app_settings(id, booking_anticipation_days) values (1, 1);

-- Function to create a new profile for a new user
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 'RESIDENT');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function when a new user signs up
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
